04-Apr-24 09:25:43 - ERROR - An unknown error occured in load_credentials: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/home/developer/Documents/repository/my-unicorn/cls/decorators.py", line 9, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/developer/Documents/repository/my-unicorn/cls/AppImageDownloader.py", line 172, in load_credentials
    self.appimage_folder = os.path.expanduser(self.appimage_folder)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 232, in expanduser
TypeError: expected str, bytes or os.PathLike object, not NoneType
